-- Master work catalog — every artwork gets logged here first (whether or
-- not it's ever listed in the shop), with a collision-proof number per
-- category so "Landscape 07" can only ever exist once.
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query).

create table if not exists catalog (
  id bigint generated by default as identity primary key,
  category text not null,
  number integer not null,
  title text,
  year integer,
  status text not null default 'catalog'
    check (status in ('catalog', 'listed', 'sold', 'archived')),
  product_id bigint references products(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  unique (category, number)
);

create index if not exists catalog_category_idx on catalog (category);
