-- Customer reviews per product. Anyone can submit a review; it only shows
-- up publicly (and in the Product structured data) once an admin approves
-- it, so the site never publishes unmoderated text under Manfred's name.
-- Run this once in the Supabase SQL Editor (Project → SQL Editor → New query).

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  author_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reviews_product_id_idx on reviews (product_id);
create index if not exists reviews_approved_idx on reviews (approved);

alter table reviews enable row level security;

create policy "Reviews public read (approved only)"
  on reviews for select
  using (approved = true);

create policy "Reviews public submit"
  on reviews for insert
  with check (approved = false);

create policy "Reviews authenticated read all"
  on reviews for select
  using (auth.role() = 'authenticated');

create policy "Reviews authenticated update"
  on reviews for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "Reviews authenticated delete"
  on reviews for delete
  using (auth.role() = 'authenticated');
